/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffos.kontakti.view;

import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import ffos.kontakti.controller.ObradaKontakt;
import ffos.kontakti.controller.ObradaVrstaKontakta;
import ffos.kontakti.model.Kontakt;
import ffos.kontakti.model.VrstaKontakta;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivana
 */
public class FormaKontakt extends javax.swing.JFrame {

    private ObradaKontakt obrada;
    private ObradaVrstaKontakta obradaVrste;
    private Kontakt z;

    public Kontakt getKontakt() {
        return z;
    }

    /**
     * Creates new form FormaKontakt
     */
    public FormaKontakt() {
        initComponents();
        obrada = new ObradaKontakt();
        obradaVrste = new ObradaVrstaKontakta();
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        for (VrstaKontakta vk : obradaVrste.getVrsteKontakta()) {
            m.addElement(vk);
        }
        cmbVrstaKontakta.setModel(m);
        ucitaj();
    }

    private void ucitaj() {
        DefaultListModel m = new DefaultListModel();
        for (Kontakt vk : obrada.getKontakti()) {
            m.addElement(vk);
        }
        lstKontakt.setModel(m);
        lstKontakt.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstKontakt = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBroj = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbVrstaKontakta = new javax.swing.JComboBox<>();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnPromjeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstKontakt.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstKontaktValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstKontakt);

        jLabel1.setText("Ime");

        jLabel2.setText("Prezime");

        jLabel3.setText("Broj");

        jLabel4.setText("Datum unosa");

        jLabel5.setText("Vrsta kontakta");

        cmbVrstaKontakta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDodaj.setText("Dodaj");
        btnDodaj.setToolTipText("");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.setToolTipText("");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnPromjeni.setText("Promjeni");
        btnPromjeni.setToolTipText("");
        btnPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(txtDatum)
                                .addComponent(jLabel1)
                                .addComponent(txtIme)
                                .addComponent(jLabel3)
                                .addComponent(txtBroj)
                                .addComponent(jLabel2)
                                .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbVrstaKontakta, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnObrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPromjeni))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbVrstaKontakta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnObrisi)
                    .addComponent(btnPromjeni))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void spremi() {
        obrada.spremi(z);

        ucitaj();
    }
    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        Kontakt vk = new Kontakt();
        SimpleDateFormat df = new SimpleDateFormat("dd.MM.yyyy");
        df.setLenient(false);
        vk.setIme(txtIme.getText());
        vk.setPrezime(txtPrezime.getText());
        vk.setBroj(Integer.parseInt(txtBroj.getText()));
        try {
            vk.setDatumUnosa(df.parse(txtDatum.getText()));
        } catch (ParseException ex) {
            JOptionPane.showConfirmDialog(getRootPane(), "Niste unijeli dobar datum");
        }

        DefaultComboBoxModel m = (DefaultComboBoxModel) cmbVrstaKontakta.getModel();
        vk.setVrstakontakta((VrstaKontakta) m.getElementAt(cmbVrstaKontakta.getSelectedIndex()));
        obrada.spremi(vk);
        ucitaj();
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        Kontakt vk;
        try {
            DefaultListModel m = (DefaultListModel) lstKontakt.getModel();
            vk = (Kontakt) m.get(lstKontakt.getSelectedIndex());
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
            return;
        }
        try {
            obrada.obrisi(vk);
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }

        ucitaj();
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniActionPerformed
        Kontakt vk;
        try {
            DefaultListModel m = (DefaultListModel) lstKontakt.getModel();
            vk = (Kontakt) m.get(lstKontakt.getSelectedIndex());
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
            return;
        }

        SimpleDateFormat df = new SimpleDateFormat("dd.MM.yyyy");
        df.setLenient(false);
        vk.setIme(txtIme.getText());
        vk.setPrezime(txtPrezime.getText());
        vk.setBroj(Integer.parseInt(txtBroj.getText()));

        try {
            vk.setDatumUnosa(df.parse(txtDatum.getText()));
        } catch (ParseException ex) {
            JOptionPane.showConfirmDialog(getRootPane(), "Niste unijeli dobar datum");
        }

        DefaultComboBoxModel m = (DefaultComboBoxModel) cmbVrstaKontakta.getModel();
        vk.setVrstakontakta((VrstaKontakta) m.getElementAt(cmbVrstaKontakta.getSelectedIndex()));

        this.z = vk;
        ucitaj();

    }//GEN-LAST:event_btnPromjeniActionPerformed

    private void lstKontaktValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstKontaktValueChanged
        Kontakt vk;
        try {
            SimpleDateFormat df = new SimpleDateFormat("dd.MM.yyyy");
            df.setLenient(false);

            DefaultListModel m = (DefaultListModel) lstKontakt.getModel();
            vk = (Kontakt) m.get(lstKontakt.getSelectedIndex());
            txtIme.setText(vk.getIme());
            txtPrezime.setText(vk.getPrezime());
            txtBroj.setText(vk.getBroj()+"");
            txtDatum.setText(vk.getDatumUnosa()+ "");

            DefaultComboBoxModel mo = (DefaultComboBoxModel) cmbVrstaKontakta.getModel();
            for (int i = 0; i < mo.getSize(); i++) {
                if (((VrstaKontakta) mo.getElementAt(i)).getId() == vk.getVrstakontakta().getId()) {
                    cmbVrstaKontakta.setSelectedIndex(i);
                    break;
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lstKontaktValueChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPromjeni;
    private javax.swing.JComboBox<String> cmbVrstaKontakta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstKontakt;
    private javax.swing.JTextField txtBroj;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
}
