/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffos.kontakti.view;

import ffos.kontakti.controller.ObradaVrstaKontakta;
import ffos.kontakti.model.VrstaKontakta;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Korisnik
 */
public class FormaVrstaKontakta extends javax.swing.JFrame {

    private ObradaVrstaKontakta obrada;
    /**
     * Creates new form FormaOznaka
     */
    public FormaVrstaKontakta() {
        initComponents();
        obrada = new ObradaVrstaKontakta();
        ucitaj();
    }
private void ucitaj(){
    DefaultListModel m = new DefaultListModel();
        for (VrstaKontakta vk : obrada.getVrsteKontakta()) {
            m.addElement(vk);
        }
        lstVrstaKontakta.setModel(m);
        lstVrstaKontakta.repaint();
         }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstVrstaKontakta = new javax.swing.JList<>();
        txtNaziv = new javax.swing.JTextField();
        txtNapomena = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnPromjeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstVrstaKontakta.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstVrstaKontaktaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstVrstaKontakta);

        txtNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivActionPerformed(evt);
            }
        });

        jLabel1.setText("Naziv");

        jLabel2.setText("Napomena");

        btnDodaj.setText("Dodaj");
        btnDodaj.setToolTipText("");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnPromjeni.setText("Promjeni");
        btnPromjeni.setToolTipText("");
        btnPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(txtNaziv)
                        .addComponent(txtNapomena, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPromjeni)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(txtNapomena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodaj)
                            .addComponent(btnObrisi)
                            .addComponent(btnPromjeni))))
                .addContainerGap(319, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
              VrstaKontakta vk = new VrstaKontakta();
       vk.setNaziv(txtNaziv.getText());
       vk.setNapomena(txtNapomena.getText());
       obrada.spremi(vk);
       ucitaj();

    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        VrstaKontakta vk ;
        try {
             DefaultListModel m = (DefaultListModel)lstVrstaKontakta.getModel();
            vk = (VrstaKontakta) m.get(lstVrstaKontakta.getSelectedIndex());
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
            return;
        }
        
        vk.setNaziv(txtNaziv.getText());
        vk.setNapomena(txtNapomena.getText());
        
       obrada.obrisi(vk);
       
       ucitaj();
    }//GEN-LAST:event_btnObrisiActionPerformed
  
  
    private void btnPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniActionPerformed
        VrstaKontakta vk ;
        try {
             DefaultListModel m = (DefaultListModel)lstVrstaKontakta.getModel();
            vk = (VrstaKontakta) m.get(lstVrstaKontakta.getSelectedIndex());
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
            return;
        }
        
        vk.setNaziv(txtNaziv.getText());
        vk.setNapomena(txtNapomena.getText());
        
       obrada.spremi(vk);
       
       ucitaj();
    }//GEN-LAST:event_btnPromjeniActionPerformed

    private void txtNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazivActionPerformed

    private void lstVrstaKontaktaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstVrstaKontaktaValueChanged
          VrstaKontakta vk ;
        try {
             DefaultListModel m = (DefaultListModel)lstVrstaKontakta.getModel();
            vk = (VrstaKontakta) m.get(lstVrstaKontakta.getSelectedIndex());
            txtNapomena.setText(vk.getNapomena());
            txtNaziv.setText(vk.getNaziv());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lstVrstaKontaktaValueChanged

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPromjeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstVrstaKontakta;
    private javax.swing.JTextField txtNapomena;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables
}
